<?xml version="1.0" encoding="utf-8"?><Database Name="Betfair" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=betfair.database.windows.net;Initial Catalog=Betfair;Persist Security Info=False;User ID=lobanenok95;Pooling=False;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BetfairConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BetfairUsers" Member="BetfairUsers">
    <Type Name="BetfairUsers">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="access_level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="create_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="access_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.CheckUser" Method="CheckUser">
    <Parameter Name="param1" Type="System.String" DbType="VarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
</Database>